services:
  - type: web
    name: neuro-apt
    env: python
    region: oregon
    plan: free
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FLASK_ENV
        value: production
