services:
  - type: web
    name: neuro-apt
    env: python
    region: oregon
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FLASK_ENV
        value: production
